[ESP8266WiFiSTA] Add get broadcast IP address functionality
esp8266/Arduino pull request #6196
Opened 2019-06-11 08:24 UTC by a7md0

Calculate the broadcast IP address using the subnet mask and default gateway IP address.

2019-06-11 08:27 UTC, d-a-v approved these changes

2019-06-11 18:06 UTC, devyte requested changes
This looks like generic network calcs. I think it is therefore also applicable to the AP interface, in whichncasenit shouldn't be in the STA class.

2019-07-12 11:58 UTC, a7md0 commented
> This looks like generic network calcs. I think it is therefore also applicable to the AP interface, in whichncasenit shouldn't be in the STA class.

It would be great if you redirected me to the "generic network class" to add this code.

2019-07-12 12:30 UTC, d-a-v commented
I think what @devyte meant was to move your function into `ESP8266WiFiGeneric.cpp` with a parameter (the interface index `STATION_IF` or `SOFTAP_IF`), and add a call to this function from both ESP8266WiFiSTA and ESP8266WiFiAP with the matching interface index.

2026-08-26 17:56 UTC, TyIsI commented
I believe this one has been obsoleted by #7899?

2026-08-27 10:39 UTC, closed without merging