Fix tests in Actions
esp8266/Arduino pull request #7551
Opened 2020-08-26 13:09 UTC by ruggi99

2020-08-27 09:01 UTC, ruggi99 commented
There's an error in `fetchCertAuthority()` where the time should not be set initially, but it does.
Does it have anything to do with emulation?

2020-08-27 10:09 UTC, d-a-v commented
I restarted CI, it is now fine

2020-08-27 13:01 UTC, ruggi99 commented
Converted to draft because I need help understading why time is already set before `setClock()` call.
In the code it has been ignored for the moment.
Also running test locally, time is already set.
I Could also add a test that should fail for Public Key.

2020-08-27 13:06 UTC, d-a-v commented
Time is automatically set when esp is dhcp client and when dhcp server provides an ntp server.
Check the ntp-tz-dst example to know how to disable these features.

2020-08-27 14:48 UTC, earlephilhower commented
As part of CI, this test isn't really testing that BearSSL *works* on the host, it's checking that there are no memory leaks, uninitialized variables, or random pointers in it.  The error code we're checking is from valgrind, not the INO.  So, while I appreciate the effort I think it's kind of wasted here.

Now, if BearSSL_Validatiaon.ino is not working *on the chip itself*, we do have an error and need to fix it.

2020-08-28 15:49 UTC, earlephilhower commented
@ruggi99 can you explain the reasoning for the PR?  This example is not a test, and it's not used as such in the host environment.  It's just a vehicle to verify that BearSSL wrapper code doesn't have mem leaks/out-of-bounds accesses.

2020-08-28 16:01 UTC, ruggi99 commented
I opened this by mistake, because I wanted to open on my fork and play with Actions.
This is not a fix (title should be changed), rather an improvement of the test, so that it checks for any memory leaks, etc and also for the correct work of the SSL. This also applies to future changes to the library or SDK. It doesn't add workload.
It's extendible to all examples, to check that libraries are working correctly in the future, not only from a memory point of view

2020-08-28 16:06 UTC, ruggi99 commented
Also every example has a sort of memory leak caused by `Serial` that it's not destructed at the end of the program.
Hovewer I fixed certificates in the SSL example that wasn't working.

2020-12-05 07:29 UTC, bchampp requested changes

2020-12-05 07:29 UTC, bchampp commented on libraries/ESP8266WiFi/examples/BearSSL_Validation/BearSSL_Validation.ino
>  }
why not just return fetchURL?

2021-06-25 17:06 UTC, closed without merging