(test) WString: c_str() returns null pointer after move
esp8266/Arduino pull request #7611
Opened 2020-09-25 14:57 UTC by mcspr

target = std::move(source) does not reset source's buffer pointer back to the sso
#7553 fixes this behaviour

Added as a separate test, perhaps it could go into the existing SSO

2020-09-25 16:15 UTC, earlephilhower requested changes
Can you add a patch that fixes this to the PR?  I guess it was only discovered when the noexcept was added, allowing GCC to actually use the move method?

2020-09-26 12:53 UTC, everslick commented
Is this also affecting the WString implementation on ESP32? I think it got thee SSO patches at one point.

2020-09-27 03:11 UTC, mcspr commented
> Can you add a patch that fixes this to the PR?

Done as https://github.com/esp8266/Arduino/pull/7611/commits/7ce820aeba4b7405324cab5c7d0ae48dec94b0ee
Although, I also *could* rebase with `--author=...` rewrite of the git history and co-authred-by: $myself instead, since I repeat the existing patch almost 1-to-1

> I guess it was only discovered when the noexcept was added, allowing GCC to actually use the move method?

Exactly. Which I noticed when running tests for the library assigning the existing object throughout the loop and moving it elsewhere periodically

2020-09-27 15:10 UTC, earlephilhower approved these changes
Good catch, thanks!

2020-09-27 15:11 UTC, merged