Sanitizing HW serial's uart.cpp just a little more.
esp8266/Arduino pull request #7953
Opened 2021-03-31 13:43 UTC by dok-net

2021-03-31 13:59 UTC, d-a-v commented on cores/esp8266/uart.cpp
> +            }
This is a fix, in the sense that this case was previously returning false, right ?

2021-03-31 14:00 UTC, d-a-v approved these changes
LGTM

2021-04-04 15:16 UTC, devyte requested changes

2021-04-04 15:16 UTC, devyte commented on cores/esp8266/uart.cpp
> +            else if (tx_pin != 2)
Shouldn't this really be == 1? As it is (both master's code and this PR's code), a change with any pin different than the current will apparently succeed, but the real pin set is hardcoded to 1 below.

2021-04-04 21:06 UTC, devyte approved these changes

2021-04-04 21:17 UTC, merged