Make makdir.py work unter python3 versions below 3.5
esp8266/Arduino pull request #8194
Opened 2021-07-04 10:23 UTC by gneiss15

2021-07-08 20:22 UTC, earlephilhower requested changes
Please don't change indents with patches.  This and the other PY scripts are 4-space indented.  Spacing changes like this make it hard to review/sync up.

Also, this seems like a spot where cascaded `try (3.5+ version)` `except all (<3.5 version)` would be better than examining python version numbers.  Or, if the <3.5 version of `Path.mkdir` works on >3.5, then just change it to use that API no matter what.

2021-07-09 05:01 UTC, gneiss15 commented
1. Idents:
I corrected this. It's something that has changed by using my favorite editor.

2. Cascaded try
I don't thing that a nested try will be better here (because the function that fails is inside a loop, which will imply an exception on every iteration).
A try will have its advantage if it can't be precisely determined when the function will fail.
Here it is a well know language feature that was added with version 3.5, so the (original) call to:
pathlib.Path( ..).mkdir(.., exist_ok = True )
will fail on all versions below 3.5

3. Or, if the <3.5 version of...
OK, that was (IMHO) a better approach.
I had leave the original inside, because I would have changed a less as possible.

OK, I will upload a version that only use the <3.5 version.

2021-07-09 09:44 UTC, earlephilhower approved these changes
Thanks, this is much cleaner!

2021-07-09 10:09 UTC, d-a-v approved these changes

2021-07-09 10:09 UTC, merged