feat: adding possibility to manually set MD5 checksum for HTTP update
esp8266/Arduino pull request #8204
Opened 2021-07-09 12:51 UTC by vlastahajek

I've written [a library](https://github.com/bonitoo-io/ESP-Github-Updater) that allows updating from Github releases. To verify firmware integrity HTTPUpdater already supports MD5 checksum, but is only read from the server response header. This is not possible if there is no control of the server.
If a checksum is known from another source, it is not possible to set it. This PR allows this.

2021-07-09 17:14 UTC, earlephilhower requested changes
Looking at this change, it seems to only affect the debug output and nothing more.  The new ‘md5’ variable isn’t used outside the print, so I don’t see what the intent is here.  The description leads me to believe you wanted to override the check on some way.

2021-07-09 18:05 UTC, vlastahajek commented
@earlephilhower, thanks for the quick and detailed review. I've fixed the wrong merge of locally modified file.

2021-07-09 21:33 UTC, d-a-v approved these changes
LGTM

2021-07-11 02:43 UTC, earlephilhower approved these changes

2021-09-04 17:34 UTC, merged