MOD-WIFI-ESP8266(-DEV) update
esp8266/Arduino pull request #8297
Opened 2021-08-31 13:01 UTC by Stanimir-Petev

Added Flash mode and reset method selection options for Olimex board MOD-WIFI-ESP8266(-DEV)

2021-09-01 15:47 UTC, earlephilhower requested changes
This isn't going to pass CI.  You need to update tools/boards.txt.py and regenerate the boards.txt file from it,, not manually edit boards.txt.

Plus, it seems like you're doing both normal definitions and menu overridden ones which is not correct.  See line 5832-5833 and 5849-5850.

2021-09-03 07:13 UTC, Stanimir-Petev commented
Thank you for the advice! I wasn't aware of the python script inside the "/tools" folder.
After you mentioned about the double definitions of the FlashMode I noticed that I did the same mistake with the ResetMethod.
Now as it's done via the boards.txt.py script is there anything else that needs to be done in order to be valid?

The whole point of adding these options are that we have new flash memory chips on the board that works in those modes: ResetMethod: no dtr (aka ck); and FlashMode: QOUT.

2021-09-21 11:48 UTC, d-a-v approved these changes

2021-10-31 19:57 UTC, earlephilhower approved these changes
LGTM, thanks!

2021-10-31 20:30 UTC, merged